### ISSUE TITLE
Dựng khung bối cảnh bằng Canvas

### ISSUE THREAD

**Issue by namtruongdev** [namtruongdev/catch-idol-game-fe#2]
- [ ] Khởi tạo Canvas có kích thước 960x960 bằng p5js

**Comment by bachtuyetx7chulun** [comment]
Khung canvas 960x hơi to ô ơi

**Comment by namtruongdev** [comment]
> Khung canvas 960x hơi to ô ơi

960 gì mà to nhỉ ? Thôi cứ tạm thế đi. Mấy nữa cho lên mà thấy to thì chỉnh lại sau ô ạ

**Comment by bachtuyetx7chulun** [comment]
ok, chắc đang chạy trên playground nên nó to
